version: "3"
# If you don't use Lightning Network, you want this
# This save about 2 weeks worth of block

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: prune=500
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=500
exclusive:
  - pruning
